name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # penting biar bisa push ke repo

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Check Env Variables
      - name: Check Env
        run: |
          echo "$CSV_URL"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Run mlflow project
      - name: Run mlflow project
        run: |
          mlflow run . --env-manager=local 

      # Configure Git identity (pakai secrets)
      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"

      # Save with LFS
      - name: Save with LFS
        run: |
          git lfs install
          git lfs track "mlruns/**"
          git add .gitattributes
          git commit -m "Track large files in mlruns with Git LFS" || true
          git push origin main

      # Save models (mlruns) to repo
      - name: Save mlruns to repo
        run: |
          git add mlruns/
          git commit -m "Save mlruns from CI run" || true
          git push origin main
